// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LogGroup.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Aliyun.Api.LOG {

  /// <summary>Holder for reflection information generated from LogGroup.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class LogGroupReflection {

    #region Descriptor
    /// <summary>File descriptor for LogGroup.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LogGroupReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5Mb2dHcm91cC5wcm90byJaCgNMb2cSDAoEVGltZRgBIAEoDRIeCghDb250",
            "ZW50cxgCIAMoCzIMLkxvZy5Db250ZW50GiUKB0NvbnRlbnQSCwoDS2V5GAEg",
            "ASgJEg0KBVZhbHVlGAIgASgJIk8KCExvZ0dyb3VwEhIKBExvZ3MYASADKAsy",
            "BC5Mb2cSEAoIUmVzZXJ2ZWQYAiABKAkSDQoFVG9waWMYAyABKAkSDgoGU291",
            "cmNlGAQgASgJIi8KDExvZ0dyb3VwTGlzdBIfCgxsb2dHcm91cExpc3QYASAD",
            "KAsyCS5Mb2dHcm91cEIRqgIOQWxpeXVuLkFwaS5MT0diBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Aliyun.Api.LOG.Log), global::Aliyun.Api.LOG.Log.Parser, new[]{ "Time", "Contents" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Aliyun.Api.LOG.Log.Types.Content), global::Aliyun.Api.LOG.Log.Types.Content.Parser, new[]{ "Key", "Value" }, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::Aliyun.Api.LOG.LogGroup), global::Aliyun.Api.LOG.LogGroup.Parser, new[]{ "Logs", "Reserved", "Topic", "Source" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Aliyun.Api.LOG.LogGroupList), global::Aliyun.Api.LOG.LogGroupList.Parser, new[]{ "LogGroupList_" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Log : pb::IMessage<Log> {
    private static readonly pb::MessageParser<Log> _parser = new pb::MessageParser<Log>(() => new Log());
    public static pb::MessageParser<Log> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::Aliyun.Api.LOG.LogGroupReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public Log() {
      OnConstruction();
    }

    partial void OnConstruction();

    public Log(Log other) : this() {
      time_ = other.time_;
      contents_ = other.contents_.Clone();
    }

    public Log Clone() {
      return new Log(this);
    }

    /// <summary>Field number for the "Time" field.</summary>
    public const int TimeFieldNumber = 1;
    private uint time_;
    /// <summary>
    ///  UNIX Time Format
    /// </summary>
    public uint Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    /// <summary>Field number for the "Contents" field.</summary>
    public const int ContentsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Aliyun.Api.LOG.Log.Types.Content> _repeated_contents_codec
        = pb::FieldCodec.ForMessage(18, global::Aliyun.Api.LOG.Log.Types.Content.Parser);
    private readonly pbc::RepeatedField<global::Aliyun.Api.LOG.Log.Types.Content> contents_ = new pbc::RepeatedField<global::Aliyun.Api.LOG.Log.Types.Content>();
    public pbc::RepeatedField<global::Aliyun.Api.LOG.Log.Types.Content> Contents {
      get { return contents_; }
    }

    public override bool Equals(object other) {
      return Equals(other as Log);
    }

    public bool Equals(Log other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Time != other.Time) return false;
      if(!contents_.Equals(other.contents_)) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (Time != 0) hash ^= Time.GetHashCode();
      hash ^= contents_.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Time != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Time);
      }
      contents_.WriteTo(output, _repeated_contents_codec);
    }

    public int CalculateSize() {
      int size = 0;
      if (Time != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Time);
      }
      size += contents_.CalculateSize(_repeated_contents_codec);
      return size;
    }

    public void MergeFrom(Log other) {
      if (other == null) {
        return;
      }
      if (other.Time != 0) {
        Time = other.Time;
      }
      contents_.Add(other.contents_);
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Time = input.ReadUInt32();
            break;
          }
          case 18: {
            contents_.AddEntriesFrom(input, _repeated_contents_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the Log message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      public sealed partial class Content : pb::IMessage<Content> {
        private static readonly pb::MessageParser<Content> _parser = new pb::MessageParser<Content>(() => new Content());
        public static pb::MessageParser<Content> Parser { get { return _parser; } }

        public static pbr::MessageDescriptor Descriptor {
          get { return global::Aliyun.Api.LOG.Log.Descriptor.NestedTypes[0]; }
        }

        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        public Content() {
          OnConstruction();
        }

        partial void OnConstruction();

        public Content(Content other) : this() {
          key_ = other.key_;
          value_ = other.value_;
        }

        public Content Clone() {
          return new Content(this);
        }

        /// <summary>Field number for the "Key" field.</summary>
        public const int KeyFieldNumber = 1;
        private string key_ = "";
        public string Key {
          get { return key_; }
          set {
            key_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "Value" field.</summary>
        public const int ValueFieldNumber = 2;
        private string value_ = "";
        public string Value {
          get { return value_; }
          set {
            value_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        public override bool Equals(object other) {
          return Equals(other as Content);
        }

        public bool Equals(Content other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Key != other.Key) return false;
          if (Value != other.Value) return false;
          return true;
        }

        public override int GetHashCode() {
          int hash = 1;
          if (Key.Length != 0) hash ^= Key.GetHashCode();
          if (Value.Length != 0) hash ^= Value.GetHashCode();
          return hash;
        }

        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        public void WriteTo(pb::CodedOutputStream output) {
          if (Key.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Key);
          }
          if (Value.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Value);
          }
        }

        public int CalculateSize() {
          int size = 0;
          if (Key.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Key);
          }
          if (Value.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Value);
          }
          return size;
        }

        public void MergeFrom(Content other) {
          if (other == null) {
            return;
          }
          if (other.Key.Length != 0) {
            Key = other.Key;
          }
          if (other.Value.Length != 0) {
            Value = other.Value;
          }
        }

        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                input.SkipLastField();
                break;
              case 10: {
                Key = input.ReadString();
                break;
              }
              case 18: {
                Value = input.ReadString();
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class LogGroup : pb::IMessage<LogGroup> {
    private static readonly pb::MessageParser<LogGroup> _parser = new pb::MessageParser<LogGroup>(() => new LogGroup());
    public static pb::MessageParser<LogGroup> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::Aliyun.Api.LOG.LogGroupReflection.Descriptor.MessageTypes[1]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public LogGroup() {
      OnConstruction();
    }

    partial void OnConstruction();

    public LogGroup(LogGroup other) : this() {
      logs_ = other.logs_.Clone();
      reserved_ = other.reserved_;
      topic_ = other.topic_;
      source_ = other.source_;
    }

    public LogGroup Clone() {
      return new LogGroup(this);
    }

    /// <summary>Field number for the "Logs" field.</summary>
    public const int LogsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Aliyun.Api.LOG.Log> _repeated_logs_codec
        = pb::FieldCodec.ForMessage(10, global::Aliyun.Api.LOG.Log.Parser);
    private readonly pbc::RepeatedField<global::Aliyun.Api.LOG.Log> logs_ = new pbc::RepeatedField<global::Aliyun.Api.LOG.Log>();
    public pbc::RepeatedField<global::Aliyun.Api.LOG.Log> Logs {
      get { return logs_; }
    }

    /// <summary>Field number for the "Reserved" field.</summary>
    public const int ReservedFieldNumber = 2;
    private string reserved_ = "";
    /// <summary>
    ///  内部字段，不需要填写
    /// </summary>
    public string Reserved {
      get { return reserved_; }
      set {
        reserved_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Topic" field.</summary>
    public const int TopicFieldNumber = 3;
    private string topic_ = "";
    public string Topic {
      get { return topic_; }
      set {
        topic_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Source" field.</summary>
    public const int SourceFieldNumber = 4;
    private string source_ = "";
    public string Source {
      get { return source_; }
      set {
        source_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public override bool Equals(object other) {
      return Equals(other as LogGroup);
    }

    public bool Equals(LogGroup other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!logs_.Equals(other.logs_)) return false;
      if (Reserved != other.Reserved) return false;
      if (Topic != other.Topic) return false;
      if (Source != other.Source) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      hash ^= logs_.GetHashCode();
      if (Reserved.Length != 0) hash ^= Reserved.GetHashCode();
      if (Topic.Length != 0) hash ^= Topic.GetHashCode();
      if (Source.Length != 0) hash ^= Source.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      logs_.WriteTo(output, _repeated_logs_codec);
      if (Reserved.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Reserved);
      }
      if (Topic.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Topic);
      }
      if (Source.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Source);
      }
    }

    public int CalculateSize() {
      int size = 0;
      size += logs_.CalculateSize(_repeated_logs_codec);
      if (Reserved.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Reserved);
      }
      if (Topic.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Topic);
      }
      if (Source.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Source);
      }
      return size;
    }

    public void MergeFrom(LogGroup other) {
      if (other == null) {
        return;
      }
      logs_.Add(other.logs_);
      if (other.Reserved.Length != 0) {
        Reserved = other.Reserved;
      }
      if (other.Topic.Length != 0) {
        Topic = other.Topic;
      }
      if (other.Source.Length != 0) {
        Source = other.Source;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            logs_.AddEntriesFrom(input, _repeated_logs_codec);
            break;
          }
          case 18: {
            Reserved = input.ReadString();
            break;
          }
          case 26: {
            Topic = input.ReadString();
            break;
          }
          case 34: {
            Source = input.ReadString();
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class LogGroupList : pb::IMessage<LogGroupList> {
    private static readonly pb::MessageParser<LogGroupList> _parser = new pb::MessageParser<LogGroupList>(() => new LogGroupList());
    public static pb::MessageParser<LogGroupList> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::Aliyun.Api.LOG.LogGroupReflection.Descriptor.MessageTypes[2]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public LogGroupList() {
      OnConstruction();
    }

    partial void OnConstruction();

    public LogGroupList(LogGroupList other) : this() {
      logGroupList_ = other.logGroupList_.Clone();
    }

    public LogGroupList Clone() {
      return new LogGroupList(this);
    }

    /// <summary>Field number for the "logGroupList" field.</summary>
    public const int LogGroupList_FieldNumber = 1;
    private static readonly pb::FieldCodec<global::Aliyun.Api.LOG.LogGroup> _repeated_logGroupList_codec
        = pb::FieldCodec.ForMessage(10, global::Aliyun.Api.LOG.LogGroup.Parser);
    private readonly pbc::RepeatedField<global::Aliyun.Api.LOG.LogGroup> logGroupList_ = new pbc::RepeatedField<global::Aliyun.Api.LOG.LogGroup>();
    public pbc::RepeatedField<global::Aliyun.Api.LOG.LogGroup> LogGroupList_ {
      get { return logGroupList_; }
    }

    public override bool Equals(object other) {
      return Equals(other as LogGroupList);
    }

    public bool Equals(LogGroupList other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!logGroupList_.Equals(other.logGroupList_)) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      hash ^= logGroupList_.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      logGroupList_.WriteTo(output, _repeated_logGroupList_codec);
    }

    public int CalculateSize() {
      int size = 0;
      size += logGroupList_.CalculateSize(_repeated_logGroupList_codec);
      return size;
    }

    public void MergeFrom(LogGroupList other) {
      if (other == null) {
        return;
      }
      logGroupList_.Add(other.logGroupList_);
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            logGroupList_.AddEntriesFrom(input, _repeated_logGroupList_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
